In [26]:
import numpy as np

In [27]:
numpy_array = np.array([[0, 1], [2, 3]])

In [28]:
random_np = np.random.random((3, 4))
print(random_np)

[[0.84891665 0.12984765 0.29439851 0.67093564]
 [0.21928237 0.16898177 0.87236541 0.57662144]
 [0.38595407 0.6583583  0.61857776 0.54355613]]


In [29]:
array_ones = np.ones((2, 3))
array_zeros = np.zeros((2, 3))

In [30]:
random_np = np.random.random((6, 3))
transposed = random_np.T
print(random_np)
print(transposed)

[[0.08389126 0.68170845 0.05794216]
 [0.62399551 0.55703547 0.4803491 ]
 [0.34669167 0.52669142 0.67819257]
 [0.86064116 0.04200222 0.56925217]
 [0.97439271 0.77596191 0.54430809]
 [0.82428866 0.0043556  0.17075685]]
[[0.08389126 0.62399551 0.34669167 0.86064116 0.97439271 0.82428866]
 [0.68170845 0.55703547 0.52669142 0.04200222 0.77596191 0.0043556 ]
 [0.05794216 0.4803491  0.67819257 0.56925217 0.54430809 0.17075685]]


In [31]:
n, p, m = 1, 2, 3
random_array1 = np.random.rand(n, p)
random_array2 = np.random.rand(p, m)
dot_product = np.dot(random_array1, random_array2)
